[PATCH] Add tpm2 support to vaultboot
Changelog-public-20210907:

* Use runtime-determined boot device path in our targets
* Make boot device able to be denoted by label
* Test grsec support against linux-5.4.68
* Update all our target to use linux-5.4.68
* Introduce a common config for linux kernel
* Make the path to crypttab within initramfs overridable
* Add an option allowing automatically unlocking LUKS

Signed-off-by: HardenedVault <root@hardenedvault.net>

diff --git a/initrd/bin/gui-init b/initrd/bin/gui-init
--- a/initrd/bin/gui-init
+++ b/initrd/bin/gui-init
@@ -188,7 +188,7 @@ while true; do
     date=`date "+%Y-%m-%d %H:%M:%S"`
     seconds=`date "+%s"`
     half=`expr \( $seconds % 60 \) / 30`
-    if [ "$CONFIG_TPM" = n ]; then
+    if [ "$CONFIG_TPM" != "y" -a "$CONFIG_TPM2_TOOLS" != "y"  ]; then
       TOTP="NO TPM"
     elif [ "$half" != "$last_half" ]; then
       last_half=$half;
@@ -350,28 +350,33 @@ while true; do
   fi
 
   if [ "$totp_confirm" = "p" ]; then
-    if [ "$CONFIG_TPM" = "y" ]; then
+    if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ]; then
       if (whiptail --title 'Reset the TPM' \
-          --yesno "This will clear the TPM and TPM password, replace them with new ones!\n\nDo you want to proceed?" 16 90) then
-        /bin/tpm-reset
+		   --yesno "This will clear the TPM and TPM password, replace them with new ones!\n\nDo you want to proceed?" 16 90) then
+	 if [ "$CONFIG_TPM" = "y" ]; then
+		 /bin/tpm-reset
+	 elif [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
+		 tpmr reset
+	 fi
 
         # now that the TPM is reset, remove invalid TPM counter files
         mount_boot
         mount -o rw,remount /boot
-        rm -f /boot/kexec_rollback.txt
+        rm -f /boot/kexec_rollback.txt || true
 
-        # create Heads TPM counter before any others
-        check_tpm_counter /boot/kexec_rollback.txt \
-        || die "Unable to find/create tpm counter"
-        counter="$TPM_COUNTER"
+        if [ "$CONFIG_IGNORE_ROLLBACK" != "y" ]; then
+            # create Heads TPM counter before any others
+            check_tpm_counter /boot/kexec_rollback.txt \
+                || die "Unable to find/create tpm counter"
+            counter="$TPM_COUNTER"
 
-        increment_tpm_counter $counter \
-        || die "Unable to increment tpm counter"
+            increment_tpm_counter $counter \
+                || die "Unable to increment tpm counter"
 
-        sha256sum /tmp/counter-$counter > /boot/kexec_rollback.txt \
-        || die "Unable to create rollback file"
-        mount -o ro,remount /boot
-
+            sha256sum /tmp/counter-$counter > /boot/kexec_rollback.txt \
+                || die "Unable to create rollback file"
+            mount -o ro,remount /boot
+        fi
         update_totp
       else
         echo "Returning to the main menu"
diff --git a/initrd/etc/functions b/initrd/etc/functions
--- a/initrd/etc/functions
+++ b/initrd/etc/functions
@@ -22,8 +22,8 @@ recovery() {
 	# ensure /tmp/config exists for recovery scripts that depend on it
 	touch /tmp/config
 
-	if [ "$CONFIG_TPM" = y ]; then
-		tpm extend -ix 4 -ic recovery
+	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ]; then
+		tpmr extend -ix 4 -ic recovery
 	fi
 
 	while [ true ]
@@ -47,7 +47,11 @@ pause_recovery() {
 }
 
 pcrs() {
-	head -8 /sys/class/tpm/tpm0/pcrs
+	if [ "$CONFIG_TPM" = "y" ]; then
+		head -8 /sys/class/tpm/tpm0/pcrs
+	elif [ "$CONFIG_TPM2_TOOLS" = "y" ]; then
+		tpm2 pcrread sha256
+	fi
 }
 
 confirm_totp()
@@ -62,7 +66,7 @@ confirm_totp()
 		date=`date "+%Y-%m-%d %H:%M:%S"`
 		seconds=`date "+%s"`
 		half=`expr \( $seconds % 60 \) / 30`
-		if [ "$CONFIG_TPM" != y ]; then
+		if [ "$CONFIG_TPM" != "y" -a "$CONFIG_TPM2_TOOLS" != "y" ]; then
 			TOTP="NO TPM"
 		elif [ "$half" != "$last_half" ]; then
 			last_half=$half;
@@ -124,6 +128,34 @@ enable_usb()
 	fi
 }
 
+enable_sata()
+{
+	for mod in libata libahci ahci; do
+		if ! lsmod | grep -q "^$mod " ; then
+			insmod "/lib/modules/$mod.ko" \
+				|| die "$mod: Unable to load module"
+		fi
+	done
+
+	if [ ! -z "$1" ]; then
+		exec mount "$@"
+	fi
+}
+
+enable_nvme()
+{
+	for mod in nvme-core nvme; do
+		if ! lsmod | grep -q "^$mod " ; then
+			insmod "/lib/modules/$mod.ko" \
+				|| die "$mod: Unable to load module"
+		fi
+	done
+
+	if [ ! -z "$1" ]; then
+		exec mount "$@"
+	fi
+}
+
 confirm_gpg_card()
 {
 	read \
@@ -178,7 +210,7 @@ check_tpm_counter()
 		warn "$1 does not exist; creating new TPM counter"
 		read -s -p "TPM Owner password: " tpm_password
 		echo
-		tpm counter_create \
+		tpmr counter_create \
 			-pwdo "$tpm_password" \
 			-pwdc '' \
 			-la $LABEL \
@@ -194,13 +226,13 @@ check_tpm_counter()
 
 read_tpm_counter()
 {
-	tpm counter_read -ix "$1" | tee "/tmp/counter-$1" \
+	tpmr counter_read -ix "$1" | tee "/tmp/counter-$1" \
 	|| die "Counter read failed"
 }
 
 increment_tpm_counter()
 {
-	tpm counter_increment -ix "$1" -pwdc '' \
+	tpmr counter_increment -ix "$1" -pwdc '' \
 		| tee /tmp/counter-$1 \
 	|| die "Counter increment failed"
 }
@@ -282,8 +314,10 @@ update_checksums()
 
 	# sign and auto-roll config counter
 	extparam=
-	if [ "$CONFIG_TPM" = "y" ]; then
-		extparam=-r
+	if [ "$CONFIG_TPM" = "y" -o "$CONFIG_TPM2_TOOLS" = "y" ];then
+		if [ "$CONFIG_IGNORE_ROLLBACK" != "y" ]; then
+			extparam=-r
+		fi
 	fi
 	if ! kexec-sign-config -p /boot -u $extparam ; then
 	  echo "Failed to sign default config; press Enter to continue."
@@ -292,6 +326,20 @@ update_checksums()
 
 	# switch back to ro mode
 	mount -o ro,remount /boot
+}
+
+# evaluate key-value pair like 'LABEL=boot' to real path
+# busybox's blkid only supports LABEL and UUID
+evaluate_boot_device()
+{
+	if echo "$1" | grep -q '^/'; then
+		# if $1 contains an absolute path, output it as-is
+		echo "$1"
+	else
+		key="$(echo $1 | cut -f1 -d =)"
+		value="$(echo $1 | cut -f2 -d =)"
+		blkid | grep "$key=\"$value\"" | cut -f1 -d ':'
+	fi
 }
 
 # detect and set /boot device
@@ -341,4 +389,14 @@ detect_boot_device()
 	echo "Unable to locate /boot files on any mounted disk"
 	umount /boot 2>/dev/null
 	return 1
+}
+
+lock_chip() {
+	APM_CNT=0xb2
+	COMMON_LOCK=0xcb
+	VAULT_LOCK=0xfa
+	echo "VaultFW locking"
+	io386 -o b -b x $APM_CNT $VAULT_LOCK
+	echo "Common locking"
+	io386 -o b -b x $APM_CNT $COMMON_LOCK
 }
